import type {Metadata} from 'next'
import {PageWrapper} from "@/shared/ui";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <PageWrapper>
            {children}
        </PageWrapper>
    )
}
